[package]
name = "winmux"
version = "0.1.0"
authors = ["Juan Ibiapina <juanibiapina@gmail.com>"]

[dependencies]
x11 = { version = "*", features = ["xlib"] }
libc = "*"
bitflags = "*"
log = "*"
env_logger = "*"
